### ISSUE TITLE
Where is Server side Script

### ISSUE THREAD

**Issue by ravdeepsingh22** [openshopio/openshop.io-android#15]
Where is the server side script to be uploaded on a hosting Account??

**Comment by ZelvaJan** [comment]
Hi,
server side is provided as a service on request and the pricing starts on 400 EUR / month for  0-50000 app installs. Also there is an initial implementation fee 5-7K EUR based on customisation requirements for setting up, customising and releasing the application on App Store / Google Play .

**Comment by hbakhtiyor** [comment]
@ZelvaJan  any plans to open source it?

**Comment by ZelvaJan** [comment]
@hbakhtiyor In the near future it isn't planned to open source it.

**Comment by hbakhtiyor** [comment]
@ZelvaJan sad ))

it would be great to make the mobile apps modular and wouldn't depend from your backend. 
and communities will implement woocommerce, magento, ... connectors.

**Comment by Skornos** [comment]
@hbakhtiyor thanks for the feedback 👍 We are currently working on a similar approach.

**Comment by hbakhtiyor** [comment]
@Skornos and migrate to react-native ;)
