### ISSUE TITLE
how to connect to your server

### ISSUE THREAD

**Issue by gauravagrawal-0** [openshopio/openshop.io-android#18]
can you please tell me how to connect to your server and explain the working process of an app

**Comment by ZelvaJan** [comment]
Hi,
server side is provided as a service on request and the pricing starts on 400 EUR / month for 0-50000 app installs. Also there is an initial implementation fee 5-7K EUR based on customisation requirements for setting up, customising and releasing the application on App Store / Google Play .

**Comment by hishobkar** [comment]
Hello ZelvaJan:)

**Comment by andywat** [comment]
Sorry just really new at this and even thou I'm picking things s up quite
quickly I still don't know enough and I get a lot of things wrong I'm self
tough really enjoy coding if I can call that's what I'm going so any help
would be great and sorry of I did any thing wrong and let me know only way
I'm going to learn thanks Andy.

**Comment by ZelvaJan** [comment]
@hishobkar App simply needs a server that will respond to apps requests. All needed server endpoints are defined here: http://docs.bfeshopapiconnector.apiary.io/. The server can be written in many languages like Php, Java, Python, etc. Android app has all the requests URL defined in ```api\EndPoints``` class.

**Comment by rahulsinghmzp** [comment]
@zelvajan I have a WordPress woocommerce website. How to connect my website to openshop.io app using apiary. I can see API key in my dashboard but unable to connect it with app. Please share the steps to use openshop.io app for my website using apiary. Or can u share video of the steps. Thanks in advance.

**Comment by parveensaini1** [comment]
@ZelvaJan how can i use this system for my Woocommerce website help me so that we can use openshop
