### ISSUE TITLE
How to import project to Android Studi ?

### ISSUE THREAD

**Issue by tob47** [openshopio/openshop.io-android#23]
How to import project to Android Studi ?
I'am error Error:Error:line (21)You should define KEYSTORE_PASSWORD, KEYSTORE_ALIAS and KEY_PASSWORD in gradle.

**Comment by ZelvaJan** [comment]
Hi,
if you set a "debug" build of an application you don't have to setup this properties. 
But if you want your own production ("release") build you have to create Certificates and Keystores on your own for security reasons. 
For a more information please look here: https://developer.android.com/studio/publish/app-signing.html
