### ISSUE TITLE
Retrieving Data

### ISSUE THREAD

**Issue by ghost** [openshopio/openshop.io-android#31]
How to change the names of the categories and their childs 
![screenshot_2017-01-20-22-44-40 1](https://cloud.githubusercontent.com/assets/22117811/22158431/2d1c208a-df62-11e6-9bc9-375b057b3c36.png)
Example i want to change Accessories to Electronics how can i change it??

**Comment by tugrulkarakaya** [comment]
CAtegories are retrieved from a service. Your should have your service on your server and change the url in the applicaiton to use your services. After that you can have whatever you want on categories list.

**Comment by ghost** [comment]
I don't have a service how should i get a service and how to change the urls.. Please explain me the steps how to do and if possible keep screenshots and if there is any link regarding this please inform me... Waiting for your reply..
Thank You..
