### ISSUE TITLE
how to get the backend service and is this free>?

### ISSUE THREAD

**Issue by stickylabdev** [openshopio/openshop.io-android#34]
how to get the backend service and is this free>?

**Comment by salvociaramitaro** [comment]
I don't know.. i wanna know it asap please!

**Comment by ZelvaJan** [comment]
Hi,
server side is provided as a service on request and the pricing starts on 400 EUR / month for 0-50000 app installs. Also there is an initial implementation fee 5-7K EUR based on customisation requirements for setting up, customising and releasing the application on App Store / Google Play.

**Comment by salvociaramitaro** [comment]
I want to bring an android app based on openshop.io . It's a demo,a simulation.. it's not the reality. So i just need a fake backend service for change images,description and so on

**Comment by ZelvaJan** [comment]
@Salvocr If you don't want to use our paid backend, create your own backend. Openshop.io app is opensource, so it is simple to change server url from our server to your fake server.

**Comment by stickylabdev** [comment]
i have to learn a lot
