### ISSUE TITLE
Internal server error 500

### ISSUE THREAD

**Issue by jolosastro** [openshopio/openshop.io-android#37]
Hi, http://77.93.198.186/v1.2/4/shops this url is not working

**Comment by rhonyabdullah** [comment]
Hello @jolosastro , please read this guide [how to connect](https://github.com/openshopio/openshop.io-android#how-to-connect)

**Comment by ZelvaJan** [comment]
Hi, we had problem with our server hosting, so the staging server is sometimes down. The staging server now works normally.

**Comment by Rolito75** [comment]
I have encounter again the same issue "Internal error, please try it later"

**Comment by jeffhumph** [comment]
Still getting this error.
