### ISSUE TITLE
Splash Screen Internal Error

### ISSUE THREAD

**Issue by Yasugi94** [openshopio/openshop.io-android#42]
Hi, i think http://77.93.198.186/v1.2/4/shops is not working and It always show internal error message when I start  the splash screen activity. Anyone can help me? Thanks before

**Comment by ZelvaJan** [comment]
Hi, we had problem with our server hosting, so the staging server is sometimes down. The application now works normally.

**Comment by Yasugi94** [comment]
Thank you ^^

**Comment by Rolito75** [comment]
Is your staging server down cause I am now receiving the same internal error message

**Comment by willianmascimiano** [comment]
I have the same error today.. The server IP it's correct ?

Thanks.

**Comment by praveenjntu34** [comment]
Im facing the same issue today dated 11/16/2017
