### ISSUE TITLE
Keystore password and keystore alias

### ISSUE THREAD

**Issue by ummaruje** [openshopio/openshop.io-android#43]
Gradle sync failed: You should define KEYSTORE_PASSWORD, KEYSTORE_ALIAS and KEY_PASSWORD in gradle.properties.groovy.lang.MissingPropertyException: Could not get unknown property 'KEYSTORE_PASSWORD' for SigningConfig_Decorated{name=release, storeFile=C:\Users\user\Downloads\umar\shopping\app\openshopKeystore.jks, storePassword=null, keyAlias=null, keyPassword=null, storeType=C:\Users\user\Downloads\umar\shopping\app\openshopKeystore.jks, v1SigningEnabled=true, v2SigningEnabled=true} of type com.android.build.gradle.internal.dsl.SigningConfig.

**Comment by ZelvaJan** [comment]
Hi,
if you set a "debug" build of an application you don't have to setup build properties.
But if you want your own production ("release") build you have to create Certificates and Keystores on your own for security reasons.
For a more information please look here: https://developer.android.com/studio/publish/app-signing.html
