### ISSUE TITLE
WordPress as backend

### ISSUE THREAD

**Issue by abuzer** [openshopio/openshop.io-android#48]
I wanted to ask, if i can use some php server or WordPress+WooCommerce as backend server?

**Comment by basitanwer** [comment]
You kind of can, you'll have to create a web server that serves the data in those websites or platforms

**Comment by iarunabho** [comment]
I am trying to do the same but can you compile the app in the first place I am getting grade sync error

**Comment by rahulsinghmzp** [comment]
@basitanwer I hav my wordpress woocommerce website showing json, i hav  added facebook_ap_id and  google gcm android key but i am unable to get ORGANIZATION_ID. Please help me to get my ORGANIZATION_ID.

**Comment by ZelvaJan** [comment]
You can look at apiary mock server https://bfashionapibfversion.docs.apiary.io/# there you can get some idea about dataStructure. Generally speaking this is just mobile aplication, you have to write your own server which will handle all the logic ad data for specific store -> you can remove organization id if you plan to use it just for your store.
