### ISSUE TITLE
The demo application in playstore is not the same as this one

### ISSUE THREAD

**Issue by basitanwer** [openshopio/openshop.io-android#49]
As stated in the subject, the demo application is not the same one at-least visually as available in the android playstore.

**Comment by ZelvaJan** [comment]
It is the same now.

**Comment by basitanwer** [comment]
Will you guys be uploading the openshop 2.0 version ?

**Comment by ZelvaJan** [comment]
Yes, but it will take some time before we will be able to open source it.
