### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by Rolito75** [openshopio/openshop.io-android#51]
I have encounter this error message "Internal error, please try it later"

**Comment by iarunabho** [comment]
I guess that's the error when you try to install the stable app included

**Comment by ZelvaJan** [comment]
Partially solved by connecting to apiary mock server https://bfashionapibfversion.docs.apiary.io/# Generally speaking this is just mobile aplication, you have to write your own server which will handle all the logic ad data for specific store.
