### ISSUE TITLE
Cannot Run the app code "Grade sync failed"

### ISSUE THREAD

**Issue by iarunabho** [openshopio/openshop.io-android#54]
There is some issue with the keynote or something I tried to compile the code that is available and It doesn't seem to work.

**Comment by iarunabho** [comment]
When I try to load the file I get error "Error:(21, 0) You should define KEYSTORE_PASSWORD, KEYSTORE_ALIAS and KEY_PASSWORD in gradle.properties.groovy.lang.MissingPropertyException: Could not get unknown property 'KEYSTORE_PASSWORD' for SigningConfig_Decorated{name=release, storeFile=C:\Users\KoreanJesus\Desktop\Android\openshop_android\openshop.io-android\app\openshopKeystore.jks, storePassword=null, keyAlias=null, keyPassword=null, storeType=C:\Users\KoreanJesus\Desktop\Android\openshop_android\openshop.io-android\app\openshopKeystore.jks, v1SigningEnabled=true, v2SigningEnabled=true} of type com.android.build.gradle.internal.dsl.SigningConfig.
<a href="openFile:C:\Users\KoreanJesus\Desktop\Android\openshop_android\openshop.io-android\app\build.gradle">Open File</a>"

**Comment by ghost** [comment]
Try to read the error atleast....
You can either comment the keystore lines out in the gradle or insert them.

**Comment by iarunabho** [comment]
Hi, I have already connected it to my woocommerce store but now I am
getting

   1. the app crashes when trying to load the json from woocommerce
   2. I'm receiving errors 400 and 500 from i
   3. it*
   4. ok sure, it just says database error, but this should not be the case
   because the website / store itself is working.
   5. .I am  getting unauthorized 400 error

[image: Inline image 1]
On 17-Oct-2017 10:03 PM, "Mikk Küttim" <notifications@github.com> wrote:

> Try to read the error atleast....
> You can either comment the keystore lines out in the gradle or insert them.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://app.mailtag.io/link-event?url=https%3A%2F%2Fgithub.com%2Fopenshopio%2Fopenshop.io-android%2Fissues%2F54%23issuecomment-337279971&id=c8f0bcf0-b36f-11e7-9a05-0607aba541c6>,
> or mute the thread
> <https://app.mailtag.io/link-event?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FASuKzCswjZmGmoJgMOCtIAfUvNhzcG9xks5stNbggaJpZM4PaGhD&id=c8f0be44-b36f-11e7-bcc2-0607aba541c6>
> .
>

  Sent with MailTag <http://www.mailtag.io>

**Comment by iarunabho** [comment]
<img width="1920" alt="screen shot 2017-10-12 at 2 38 09 am 1" src="https://user-images.githubusercontent.com/19630796/31684825-99436f3c-b39e-11e7-8381-238c5499ac7b.png">

**Comment by ZelvaJan** [comment]
Errors are partially solved by connecting to apiary mock server https://bfashionapibfversion.docs.apiary.io/# Generally speaking this is just mobile aplication, you have to write your own server which will handle all the logic ad data for specific store.
