### ISSUE TITLE
Internal server error 

### ISSUE THREAD

**Issue by jsanzmex** [openshopio/openshop.io-android#57]
Hello,

Since October 23, I've been receiving error code 500 (internal server error) when trying to execute the app. The same happens with the iOS version.

**Comment by mrafeie** [comment]
me too :(

**Comment by tester87** [comment]
Same to me too, anyone can help on this? appreciated.

**Comment by ZelvaJan** [comment]
Partially solved by connecting to apiary mock server https://bfashionapibfversion.docs.apiary.io/# Generally speaking this is just mobile aplication, you have to write your own server which will handle all the logic ad data for specific store.
