### ISSUE TITLE
There open source project for backend api?

### ISSUE THREAD

**Issue by keviocastro** [openshopio/openshop.io-android#61]

**Comment by samsonlarsson** [comment]
This is based on prestashop, you might wanna check it out and cnfigure one for yourself

**Comment by ZelvaJan** [comment]
Partially solved by connecting to apiary mock server https://bfashionapibfversion.docs.apiary.io/# Generally speaking this is just mobile aplication, you have to write your own server which will handle all the logic ad data for specific store.
