### ISSUE TITLE
Fail to refactor the bf section

### ISSUE THREAD

**Issue by bunhin** [openshopio/openshop.io-android#62]
Hi all,
I import the app into android studio and get successful build, but whan i try to refactor (rename package name), always fail when try to change the bf  into com,  please help how to solve this.

The error message is  .....file already exits.

I suspect that there is  "com" folder and "bf"  folder in same parent folder so whent try to refactor the com folder is already there (conatining google etc)

Please help how to do it correctly

Regards,
Bun Hin

**Comment by ZelvaJan** [comment]
You have to change whole folder structure for example: https://abhiandroid.com/androidstudio/how-to-change-package-name-android-studio.html

**Comment by bunhin** [comment]
@ZelvaJan thank you for reply, actually i did the step by step, but i will try again
