### ISSUE TITLE
Gradle sync failed

### ISSUE THREAD

**Issue by dgdesignstudio** [openshopio/openshop.io-android#63]
Hi, I'm trying to import openshop.io project in Android Studio, while importing i'm getting error.

Gradle sync failed: You should define KEYSTORE_PASSWORD, KEYSTORE_ALIAS and KEY_PASSWORD in gradle.properties.groovy.lang.MissingPropertyException: Could not get unknown property 'KEYSTORE_PASSWORD' for SigningConfig_Decorated{name=release, storeFile=/Users/malarvizhi/Downloads/openshop.io-android-master/app/openshopKeystore.jks, storePassword=null, keyAlias=null, keyPassword=null, storeType=/Users/malarvizhi/Downloads/openshop.io-android-master/app/openshopKeystore.jks, v1SigningEnabled=true, v2SigningEnabled=true} of type com.android.build.gradle.internal.dsl.SigningConfig.
				Consult IDE log for more details (Help | Show Log) (16s 765ms)

Some one please help me to solve this

**Comment by campyncheezy** [comment]
Got the same problem

**Comment by campyncheezy** [comment]
Please someone help us..

**Comment by RaminMammadzada** [comment]
You can comment out these lines in the build.gradle file:
try {
                storeFile file("openshopKeystore.jks")
                storePassword KEYSTORE_PASSWORD
                keyAlias KEYSTORE_ALIAS
                keyPassword KEY_PASSWORD
            } catch (ex) {
                throw new InvalidUserDataException("You should define KEYSTORE_PASSWORD, KEYSTORE_ALIAS and KEY_PASSWORD in gradle.properties." + ex)
            }

You can find build.gradle file inside the app folder In Project view.
Be sure to close and reopen the project after you do uncommenting.

**Comment by ZelvaJan** [comment]
Hi,
if you set a "debug" build of an application you don't have to setup build properties.
But if you want your own production ("release") build you have to create Certificates and Keystores on your own for security reasons.
For a more information please look here: https://developer.android.com/studio/publish/app-signing.html
