### ISSUE TITLE
API

### ISSUE THREAD

**Issue by alien3d** [openshopio/openshop.io-android#64]
Some api i can get at https://bfeshopapiconnector.docs.apiary.io.And the product are from XML or JSON. Quite confuse with the note.. At the main github saying xml while at the apiary saying JSON only. 
 but some not documented like  navigation_drawer,devices .. 

I can check all the code but it will take time

Want to knew is the project still alive or you allready abandon for v2 version ?

any information please @ZelvaJan

**Comment by rahulsinghmzp** [comment]
@ZelvaJan I hav my wordpress woocommerce website showing json, i hav  added facebook_ap_id and  google gcm android key but i am unable to get ORGANIZATION_ID. Please help me to get my ORGANIZATION_ID.

**Comment by ZelvaJan** [comment]
Partially solved by connecting to apiary mock server https://bfashionapibfversion.docs.apiary.io/# there you can get some idea about dataStructure. Generally speaking this is just mobile aplication, you have to write your own server which will handle all the logic ad data for specific store -> you can remove organization id.

I just helped to develop the android v1.0 application, i am not able to help with business contact or with v2.0 source code.
