### ISSUE TITLE
Error Building Application

### ISSUE THREAD

**Issue by adityabaweja** [openshopio/openshop.io-android#65]
Error:You should define KEYSTORE_PASSWORD, KEYSTORE_ALIAS and KEY_PASSWORD in gradle.properties.groovy.lang.MissingPropertyException: Could not get unknown property 'KEYSTORE_PASSWORD' for SigningConfig_Decorated{name=release, storeFile=C:\Users\***\Documents\Setups\openshop.io-android-master\openshop.io-android-master\app\openshopKeystore.jks, storePassword=null, keyAlias=null, keyPassword=null, storeType=C:\Users\***\Documents\Setups\openshop.io-android-master\openshop.io-android-master\app\openshopKeystore.jks, v1SigningEnabled=true, v2SigningEnabled=true} of type com.android.build.gradle.internal.dsl.SigningConfig.

Consult IDE log for more details (Help | Show Log)

**Comment by campyncheezy** [comment]
I have this error too. Please some help me to figure this out.

**Comment by ZelvaJan** [comment]
Hi,
if you set a "debug" build of an application you don't have to setup build properties.
But if you want your own production ("release") build you have to create Certificates and Keystores on your own for security reasons.
For a more information please look here: https://developer.android.com/studio/publish/app-signing.html
