### ISSUE TITLE
where are product endpoints

### ISSUE THREAD

**Issue by binaamir** [openshopio/openshop.io-android#68]
Hi @ZelvaJan,
I am exploring the project and read the documentation, I have few question:
1) I could not find any endpoints for products.
2) there seems to be lots of endpoints in the app, like navigation list, shop etc. but only few are listed in documentation.
3) I am planning to build a backend api on top of laravel, but could not find enough information on how to start.
4) the version 1.0 on play store does not works and give internal server error, but the v2.0 is working. but the v1.0 source code on github is available. from where can i find the v2.0 source code?

I also tried to contact on email mentioned in contact section, but did not get any response from there. Please give me answers to these questions asap because I have to develop this project for someone.

**Comment by ZelvaJan** [comment]
Partially solved by connecting to apiary mock server https://bfashionapibfversion.docs.apiary.io/# which give you some idea about endpoints. 
I just helped to develop the android v1.0 application, i am not able to help with business contact or with v2.0 source code.
