### ISSUE TITLE
connection exception not able to enter 

### ISSUE THREAD

**Issue by venkateshcool12** [openshopio/openshop.io-android#69]
Hi,

I am not able to get details from this url http://77.93.198.186/v1.2/

**Comment by aek** [comment]
That just means that the backend behind that URL has been stopped. You should think about writing your own backend and integrate it with your eCommerce of choice. I could say that having done that it works with little changes in the code

**Comment by ZelvaJan** [comment]
Partially solved by connecting to apiary mock server https://bfashionapibfversion.docs.apiary.io/#
